import { Task, BattleScenario } from '../types';
import { TaskFactory } from './taskFactory';

export const BATTLE_SCENARIOS: BattleScenario[] = [
  // === GEOMETRIE BATTLES ===
  {
    id: 'speed_geometry',
    title: 'Speed Polygon Duel',
    tagline: '3 Formen · 45 Sekunden Fokus',
    description: 'Klassifiziere blitzschnell Vierecke, erkenne Eigenschaften und entscheide, wer zum Geodreieck greift.',
    unitId: 'u1',
    unitTitle: 'Figuren verstehen',
    stake: 25,
    rounds: 3,
    icon: '⚡',
    difficulty: 'Mittel',
    modifiers: ['Timer 45s', 'Keine Hints', 'Sofort-Feedback'],
    tags: ['Figuren', 'Grundlagen', 'Tempo'],
  },
  {
    id: 'angle_meltdown',
    title: 'Angle Meltdown',
    tagline: '4 Winkel · 1 Chance',
    description: 'Nebenwinkel, Scheitelwinkel und Thales – wer schneller begründet, kassiert den Pot.',
    unitId: 'u2',
    unitTitle: 'Winkel & Beziehungen',
    stake: 35,
    rounds: 4,
    icon: '📐',
    difficulty: 'Schwer',
    modifiers: ['±5° Toleranz', 'Auto-Hint gesperrt'],
    tags: ['Winkel', 'Beweis', 'Beziehungen'],
  },
  {
    id: 'area_assault',
    title: 'Area Assault',
    tagline: '5 Flächen · Zerlegungs-Master',
    description: 'Zerlege komplexe Formen in Rechtecke und Trapeze. Wer die meisten Flächen richtig berechnet, gewinnt.',
    unitId: 'u3',
    unitTitle: 'Flächen & Terme',
    stake: 30,
    rounds: 5,
    icon: '🔷',
    difficulty: 'Mittel',
    modifiers: ['Zerlegung erforderlich', 'Terme vereinfachen'],
    tags: ['Flächen', 'Zerlegung', 'Terme'],
  },
  {
    id: 'volume_drop',
    title: 'Volume Drop',
    tagline: '2 Körper · hoher Einsatz',
    description: 'Berechne Mantel- und Volumenflächen gegen die Zeit. Fehler kosten sofort den Lauf.',
    unitId: 'u4',
    unitTitle: 'Körper & Oberflächen',
    stake: 45,
    rounds: 2,
    icon: '🧊',
    difficulty: 'Schwer',
    modifiers: ['Runden auf 1 Nachkommastelle', 'Nur Eingaben'],
    tags: ['Volumen', 'Oberfläche', 'Sachaufgaben'],
  },
  {
    id: 'scaling_relay',
    title: 'Scaling Relay',
    tagline: '3 Streckungen · Kombi-Check',
    description: 'Maßstab, Flächenfaktor und Prozent – alles in einem Lauf. Perfekt für Transformation-Fans.',
    unitId: 'u5',
    unitTitle: 'Ähnlichkeit & Skalierung',
    stake: 30,
    rounds: 3,
    icon: '📊',
    difficulty: 'Mittel',
    modifiers: ['k-Analyse', 'Vergleiche', 'Übertrag'],
    tags: ['Skalierung', 'Verhältnisse', 'Transfer'],
  },
  {
    id: 'reality_check',
    title: 'Reality Check',
    tagline: '3 Alltags-Probleme · Transfer-Test',
    description: 'Hausbau, Poolbefüllung, Zeltlager – wer Mathe im echten Leben anwendet, dominiert.',
    unitId: 'u6',
    unitTitle: 'Alltags-Geometrie',
    stake: 40,
    rounds: 3,
    icon: '🏗️',
    difficulty: 'Schwer',
    modifiers: ['Sachaufgaben', 'Einheiten beachten', 'Runden sinnvoll'],
    tags: ['Transfer', 'Modellierung', 'Alltag'],
  },

  // === POTENZEN BATTLES ===
  {
    id: 'power_rush',
    title: 'Power Rush',
    tagline: '4 Potenzgesetze · Exponenten-Chaos',
    description: 'Multipliziere, dividiere und potenziere Potenzen. Wer die Gesetze beherrscht, kassiert den Jackpot.',
    unitId: 'u_potenzen_01',
    unitTitle: 'Zahlen-Sortierer',
    stake: 35,
    rounds: 4,
    icon: '⚡',
    difficulty: 'Mittel',
    modifiers: ['Potenzgesetze', 'Negative Exponenten', 'Keine Taschenrechner'],
    tags: ['Potenzen', 'Gesetze', 'Exponenten'],
  },
  {
    id: 'root_warrior',
    title: 'Root Warrior',
    tagline: '3 Wurzeln · Radikal-Duell',
    description: 'Vereinfache Wurzeln, wandle in Potenzen um und berechne n-te Wurzeln. Radikal gegen Radikal.',
    unitId: 'u_potenzen_01',
    unitTitle: 'Zahlen-Sortierer',
    stake: 40,
    rounds: 3,
    icon: '√',
    difficulty: 'Schwer',
    modifiers: ['Wurzelgesetze', 'Rationalisierung', 'n-te Wurzeln'],
    tags: ['Wurzeln', 'Radikale', 'Vereinfachung'],
  },
  {
    id: 'scientific_showdown',
    title: 'Scientific Showdown',
    tagline: '5 Zahlen · Zehnerpotenz-Master',
    description: 'Wandle zwischen normaler und wissenschaftlicher Schreibweise um. Präzision ist alles.',
    unitId: 'u_potenzen_01',
    unitTitle: 'Zahlen-Sortierer',
    stake: 30,
    rounds: 5,
    icon: '🔬',
    difficulty: 'Mittel',
    modifiers: ['Zehnerpotenzen', 'Umwandlung', 'Genauigkeit'],
    tags: ['Wissenschaft', 'Zehnerpotenzen', 'Notation'],
  },

  // === QUADRATISCH BATTLES ===
  {
    id: 'parabel_perfection',
    title: 'Parabel Perfection',
    tagline: '3 Parabeln · Scheitelpunkt-Jagd',
    description: 'Finde Scheitelpunkte, analysiere Öffnung und bestimme Symmetrieachsen. Parabel-Meister gesucht!',
    unitId: 'u_quadratisch_01',
    unitTitle: 'Parabel-Basics',
    stake: 40,
    rounds: 3,
    icon: '📈',
    difficulty: 'Mittel',
    modifiers: ['SPF & AF', 'Scheitelpunkt', 'Symmetrie'],
    tags: ['Parabeln', 'Scheitelpunkt', 'Funktionen'],
  },
  {
    id: 'nullstellen_nightmare',
    title: 'Nullstellen Nightmare',
    tagline: '4 Funktionen · pq-Formel-Fury',
    description: 'Berechne Nullstellen mit pq-Formel, prüfe Diskriminanten und löse quadratische Gleichungen.',
    unitId: 'u_quadratisch_01',
    unitTitle: 'Parabel-Basics',
    stake: 45,
    rounds: 4,
    icon: '🎯',
    difficulty: 'Schwer',
    modifiers: ['pq-Formel', 'Diskriminante', 'Lösungsmenge'],
    tags: ['Nullstellen', 'pq-Formel', 'Gleichungen'],
  },
  {
    id: 'transformation_tornado',
    title: 'Transformation Tornado',
    tagline: '3 Transformationen · Streckung & Verschiebung',
    description: 'Erkenne Streckungen, Verschiebungen und Spiegelungen. Wer die Transformationen liest, gewinnt.',
    unitId: 'u_quadratisch_01',
    unitTitle: 'Parabel-Basics',
    stake: 35,
    rounds: 3,
    icon: '🌀',
    difficulty: 'Mittel',
    modifiers: ['Streckfaktor a', 'Verschiebung', 'Spiegelung'],
    tags: ['Transformation', 'Streckung', 'Verschiebung'],
  },

  // === SPECIAL BATTLES ===
  {
    id: 'mixed_mayhem',
    title: 'Mixed Mayhem',
    tagline: '5 Aufgaben · Alles-Mix',
    description: 'Eine wilde Mischung aus Geometrie, Potenzen und quadratischen Funktionen. Der ultimative Test!',
    unitId: 'u1', // Uses first unit as base, but tasks will be mixed
    unitTitle: 'Mixed Challenge',
    stake: 50,
    rounds: 5,
    icon: '🎲',
    difficulty: 'Schwer',
    modifiers: ['Alles-Mix', 'Hoher Einsatz', 'Master-Level'],
    tags: ['Mix', 'Challenge', 'Master'],
  },
];

export function getBattleScenarioById(id: string): BattleScenario | undefined {
  return BATTLE_SCENARIOS.find(s => s.id === id);
}

export function generateBattleTaskBundle(scenarioId: string, overrideRounds?: number): Task[] {
  const scenario = getBattleScenarioById(scenarioId);
  if (!scenario) return [];
  const rounds = overrideRounds && overrideRounds > 0 ? overrideRounds : scenario.rounds;
  return TaskFactory.getBattleTasksForUnit(scenario.unitId, rounds);
}


